# Generated by Django 4.1.3 on 2023-01-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_newspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='cat_id',
            field=models.IntegerField(null=True),
        ),
    ]
