# Generated by Django 4.1.3 on 2023-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_newspage_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='user_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
