# Generated by Django 4.1.3 on 2023-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_newspage_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='cat_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
