# Generated by Django 4.1.5 on 2023-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_newspage_new_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='newspage',
            name='image',
            field=models.ImageField(null=True, upload_to='myimage'),
        ),
    ]
