# Generated by Django 4.1.5 on 2023-01-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_newspage_time_alter_newspage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='cat_id',
            field=models.IntegerField(),
        ),
    ]
