# Generated by Django 4.1.5 on 2023-01-21 15:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_alter_newspage_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
